# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.10
        environment:
            PIPENV_VENV_IN_PROJECT: true
    working_directory: ~/squirrel-maze

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}
      - run:
          name: install dependencies
          command: |
            poetry install
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - "/home/circleci/.cache/pypoetry/virtualenvs"
      - run:
          name: Analysis
          command: |
            make analysis
      - run:
          name: Lint
          command: |
            make check
      - run:
          name: Tests
          command: |
            make test
      - store_test_results:
          path: artifacts
      - store_artifacts:
          path: artifacts
